# Generated by Django 5.1.15 on 2026-02-28 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clock_player',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='clock.player')),
            ],
            options={
                'db_table': 'clock_tournament_entry',
                'ordering': ['joined_at'],
            },
        ),
    ]
