# Generated by Django 5.1.15 on 2026-03-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_tournament_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tournaments', to='clock.player'),
        ),
    ]
